### ISSUE TITLE
Setup Issues

### ISSUE THREAD

**Issue by ninjada** [saltstack-formulas/ec2-autoscale-reactor#3]
Hello, I have a number of salt ec2 auto scale groups that I am trying to saltify. However, I'm having a few issues attempting to set this up. This formula is the most recent I can find but i'm unsure if this is still the most current or recommended method for having salt bootstrap new instances deployed within an ec2 vpc autoscale group?

is the develop branch still required? i'm just running the latest stable given it seems quite old..

here are my salt version details:
```
$ salt --versions-report
           Salt: 2015.5.0
         Python: 2.6.9 (unknown, Apr  1 2015, 18:16:00)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
```

the main problem I am having is setting up SNS over SSL. your documentation makes no mention of configuring salt-api for SSL but salt-api appears to needs a crt & key or for ssl to be explicitly disabled.

ive got the system working fine running salt-api with disable_ssl true and an SNS endpoint over HTTP, i receive the notifications and reactor goes to work, but that highlights my main concern with this method going over public internet.. even with SSL i'm not sure i'd want this, as it poses the issue of locking my salt instance port 8080 down to the SNS IP range, something which is notoriously difficult. Ideally i'd want SNS hitting my salt instance privately or utilizing IAM roles but i am unsure that is possible at this stage.

but first things first, trying to enable salt-api running with SSL, i've tried about 7 differently generated selfsigned SSL certs and also one proper wildcard ssl in use for my primary domain. All have resulted in salt-api throwing the following errors when receiving messages from SNS:

```
[ERROR   ] [14/Jul/2015:05:33:53] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1837, in start
    self.tick()
  File "/usr/lib/python2.6/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1902, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/lib/python2.6/site-packages/cherrypy/wsgiserver/ssl_builtin.py", line 52, in wrap
    keyfile=self.private_key, ssl_version=ssl.PROTOCOL_SSLv23)
  File "/usr/lib64/python2.6/ssl.py", line 338, in wrap_socket
    suppress_ragged_eofs=suppress_ragged_eofs)
  File "/usr/lib64/python2.6/ssl.py", line 120, in __init__
    self.do_handshake()
  File "/usr/lib64/python2.6/ssl.py", line 279, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:493: error:14094416:SSL routines:SSL3_READ_BYTES:sslv3 alert certificate unknown
```

this includes using the salt module 'salt-call tls.create_self_signed_cert' to generate one, no dice. 

1) what is the requirement here for a secure connection between SNS and my salt instance?
2) is it possible to have SNS communicate privately ore more securely with my salt instance because this doesn't seem ideal?
3) whats the most up to date method of having salt/salt-cloud etc. take charge of autoscaling?

**Comment by iggy** [comment]
Generally, you shouldn't consider the formulas as a plug-and-play solution to a problem. They are more of a starting point to give people a head start on solving their problems.

**Comment by techhat** [comment]
The develop branch is no longer required. Also, I concur with @iggy, concerning starting points.

Instructions for SSL are located at http://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html (look for `ssl_key` and `ssl_crt`).

@whiteinge, do you have any more information for @ninjada?

**Comment by whiteinge** [comment]
> salt-api appears to needs a crt & key or for ssl to be explicitly disabled.

This is correct. You either need to specify an SSL key or you need to disable SSL.

> what is the requirement here for a secure connection between SNS and my salt instance?

If SNS lets you use an unsecured connection that is your prerogative. Since sensitive data is going over the wire, I would recommend against doing that.

> `SSLError: [Errno 1] _ssl.c:493: error:14094416:SSL routines:SSL3_READ_BYTES:sslv3 alert certificate unknown`

The error looks like the known issue with CherryPy detailed in the documentation linked above. Check your version of CherryPy and see the documentation about CherryPy and SSL.

**Comment by ninjada** [comment]
i'm running amazon linux and latest cherrypy is 3.2.2-3, which should be prior to that issue?

**Comment by whiteinge** [comment]
Glad you got it working. CherryPy itself does not care that the cert is untrusted but the connecting client will need to be told to ignore invalid certs.

> What are the recommendations to secure this setup beyond SSL?

iptables rules to perform IP restrictions.
